### ISSUE TITLE
[Question] how to capture `client` instance before any steps have been executed

### ISSUE THREAD

**Issue by pendenaor** [mucsi96/nightwatch-api#14]
I'm currently migrating my bdd test (based on the cucumber example) and i want to create some page urls with `url` property set in global test settings, eg:

```
const pageUrls = {
  'application page': `${url}/`,
  'login page': `${url}/login`,
  'dashboard page': `${url}/main/dashboard`
}
```

**Comment by mucsi96** [comment]
Why you don’t create a simple node module with these constants and import it where needed?

**Comment by mucsi96** [comment]
You can add the url also to this module. And import it in nightwatch configuration

**Comment by pendenaor** [comment]
I have some troubles to understand what to do.
Below a sample of my code :

```
import { client } from 'nightwatch-api';
import { defineStep } from 'cucumber';

const { url } = client.globals; // <= BOOM!

const pageNames = {
  'application page': `${url}/`,
  'login page': `${url}/login`,
  'dashboard page': `${url}/main/dashboard`
}

defineStep(/^I (?:browse|open|visit).*? `(.*?)`$/, async pageName => {
  console.log(pageNames[pageName])
});
```

When i run this code, it raises an exception
```
Error: Nightwatch client is not ready.
              Looks like function "createSession" did not succeed or was not called yet.
    at Object.get (C:\Public\Repo\sinoc_ui-test\node_modules\nightwatch-api\lib\proxy.js:21:17)
    at Object.<anonymous> (C:/Public/Repo/sinoc_ui-test/step-definitions/steps.js:5:24)
    at Module._compile (module.js:652:30)
    at loader (C:\Public\Repo\sinoc_ui-test\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Public\Repo\sinoc_ui-test\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Public\Repo\sinoc_ui-test\node_modules\cucumber\src\cli\index.js:63:42
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\Public\Repo\sinoc_ui-test\node_modules\cucumber\src\cli\index.js:63:22)
    at Cli.<anonymous> (C:\Public\Repo\sinoc_ui-test\node_modules\cucumber\src\cli\index.js:78:37)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Public\Repo\sinoc_ui-test\node_modules\bluebird\js\release\util.js:16:23)
```

**Comment by pratyush23** [comment]
I am also facing the same issue while running cucumber tests using nightwatch-api. Can we please get a solution for this. Thanks

**Comment by spnraju** [comment]
Hi @pendenaor and @pratyush23 , are you still facing this issue? If yes, could you point me to a repo with sample project with similar config?

**Comment by hardy12994** [comment]
@spnraju @mucsi96 i am facing the same issue
Looks like function "createSession" did not succeed or was not called yet.
( i am trying to attach vscode debugger with nightwatch test case with `jest` )

**Comment by KatiKop** [comment]
@mucsi96 I am facing this issue, too.
My tests need the client.globals to know where they have to start. As an example I am checking the currently used .env File in my nightwatch.conf. Afterwards I set the URL dynamically. 

I have also to distinguish between some things and therefor I am using boolean values.

Example for my config:
```javascript
globals: {
                url: isStagingEnvironment ? 'www.example.com' : 'http://localhost',
                apiUrlApplicant: process.env.URL_APPLICANT,
                apiTokenApplicant: process.env.API_TOKEN,
                useNetworkStubs,
                isNotMocked,
                isStagingEnvironment,
            },
````
Example for a using in my step files:
```javascript
if (client.globals.isStagingEnvironment) {
        client.expect.element(_SELECTOR_).to.be.visible.before(DEFAULT_WAIT_IN_MS);
    }
```
Example for a using in my helper files:
```javascript
const { client } = require('nightwatch-cucumber');

const { url } = client.globals;

module.exports = {
    'applications page': `${url}/.../...`,
....
```

**Comment by gornelex** [comment]
Hi @mucsi96 

First, thanks a lot for this new package API. Looks interesting. 
I don't know if my problem is similar but after did the configurations I could not run steps files when I am using page object model.

I am trying to update my framework test from the old "Nightwatch-Cucumber (deprecated)" to this new "Nightwatch-api".
After run my step test, I am facing the issue:

`Error: Nightwatch client is not ready.
              Looks like function "createSession" did not succeed or was not called yet.`

Basically, this was working fine before in old "Nightwatch-Cucumber (deprecated)" but in this new api is not running:

This is the code that I am using in my step file:

`const { client } = require('nightwatch-api');
const { Given, Then, When } = require('cucumber');
var core = require('../../../../../pages/core'); //calling the file when I have the code and function to login
core(client).loginRequired(); //initialize the login function`

Is there something that I am not considering to point correctly to my page object?

Thanks in advance for your help!

**Comment by spnraju** [comment]
Hi @gornelex , thanks for reaching out. I see that you are facing issues in migration. Please note that nightwatch-api is a lot different than that of nightwatch-cucumber. Please follow the examples provided in the repo. if you still face the issue, an example setup will help in understanding it better. Please let us know.
