### ISSUE TITLE
Edge, Internet Explorer and Opera are not supported

### ISSUE THREAD

**Issue by ErikGrigoriev** [mucsi96/nightwatch-api#18]
Hi! I'm trying to migrate from nightwatch-cucumber to nightwatch-api, and I have faced an Issue that Edge,Opera and Internet Explorer are not working. Here is my nightwatch.conf.js:

'const chromedriver = require('chromedriver');
const geckodriver = require('geckodriver');

module.exports = {
    output_folder: 'reports',
    page_objects_path: 'tests/page_objects',
    globals_path: 'tests/globals.js',
    custom_commands_path: [
        'tests/custom_commands'
    ],
  test_settings: {
    default: {
      webdriver: {
        start_process: true,
        server_path: chromedriver.path,
        cli_args: ['--port=4444']
      },
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          args: ['disable-gpu']
        }
      }
    },
      opera: {
          webdriver: {
              server_path: "webDriver/operadriver.exe"
          },
          desiredCapabilities: {
              browserName: 'opera',
              javascriptEnabled: true,
              acceptSslCerts: true,
              operaOptions: {
                  binary: "C:/Users/e.grigoryev.EVIA/AppData/Local/Programs/Opera/launcher.exe"
              }
          }
      },
      edge: {
          webdriver: {
              server_path: "webDriver/MicrosoftWebDriver.exe"
          },
          desiredCapabilities: {
              browserName: 'MicrosoftEdge',
              javascriptEnabled: true,
              acceptSslCerts: true
          }
      },
      ie: {
          webdriver: {
              server_path: "webDriver/IEDriverServer32.exe"
          },
          desiredCapabilities: {
              browserName: 'internet explorer',
              javascriptEnabled: true,
              acceptSslCerts: true,
              nativeEvents: false,
              enablePersistentHover: true
          }
      },
      safari: {
          desiredCapabilities : {
              browserName : "safari",
              javascriptEnabled : true,
              acceptSslCerts : true
          }
      }
  }
};'

setup.js:
'import { setDefaultTimeout, AfterAll, BeforeAll } from 'cucumber';
import { createSession, closeSession } from 'nightwatch-api';

setDefaultTimeout(60000);

BeforeAll(async () => {
  await createSession('edge');
});

AfterAll(async () => {
  await closeSession();
});'

server.js:
'import { startWebDriver } from 'nightwatch-api';

startWebDriver('edge').catch(err => console.log(err));'

package.json:
'{
  "name": "nightwatch-api-cucumber",
  "version": "1.0.0",
  "description": "Demonstration for using Nightwatch API from CucumberJS test runner",
  "main": "nightwatch.conf.js",
  "scripts": {
    "test:setup": "babel-node server.js",
    "test:run": "cucumber-js tests/features/ --tags \"@Test\" --require-module babel-core/register --require tests/support --require tests/step-definitions --format node_modules/cucumber-pretty -f json:reports/cucumber.json",
    "test": "start-server-and-test test:setup http-get://localhost:4444/status test:run",
    "report": "npm-run-all test e2e-report --continue-on-error",
    "e2e-report": "node html-reports/create-html-report.js"
  },
  "repository": "git@github.com:mucsi96/nightwatch-api.git",
  "author": "Igor Mucsicska <mucsi_96@yahoo.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "chromedriver": "^2.40.0",
    "cucumber": "^4.2.1",
    "cucumber-html-reporter": "^4.0.4",
    "cucumber-pretty": "^1.4.4",
    "geckodriver": "^1.12.2",
    "nightwatch": "1.0.6",
    "nightwatch-api": "latest",
    "start-server-and-test": "^1.5.0"
  },
  "dependencies": {
    "npm-run-all": "^4.1.3"
  }
}'

Error message:
Error: Unsupported browser: MicrosoftEdge. There is no available driver.
    at WDServer.createInstance (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\runner\webdriver-server.js:87:15)
    at new WDServer (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\runner\webdriver-server.js:18:26)
    at testEnvArray.forEach.testEnv (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\runner\webdriver-server.js:40:41)
    at Array.forEach (<anonymous>)
    at Function.createInstances (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\runner\webdriver-server.js:35:18)
    at CliRunner.setupConcurrency (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\runner\cli\cli.js:184:17)
    at CliRunner.setup (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\runner\cli\cli.js:97:10)
    at createRunner (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch-api\lib\client.js:45:12)
    at startWebDriver (C:\dev\projects\nightwatch-api\nightwatch-api\examples\cucumber\node_modules\nightwatch-api\lib\client.js:52:3)
    at Object.<anonymous> (C:/dev/projects/nightwatch-api/nightwatch-api/examples/cucumber/server.js:3:1)

Should I run it differently for those browsers?

**Comment by ErikGrigoriev** [comment]
No they are up to date and the Path is correct. Issue is actally from this part of code at "webdriver-server.js":
  ```
createInstance() {
    if (this.isUsingSeleniumServer()) {
      return new SeleniumServer(this.settings.selenium);
    }

    if (!this.settings.webdriver.start_process) {
      return null;
    }

    let browserName = this.settings.desiredCapabilities.browserName;
    let WebDriverImpl;

    switch (browserName) {
      case BrowserName.CHROME:
        WebDriverImpl = ChromeDriver;
        break;

      case BrowserName.FIREFOX:
        WebDriverImpl = GeckoDriver;
        break;

      default:
        throw new Error(`Unsupported browser: ${browserName}. There is no available driver.`);
    }

    if (WDServer.concurrencyEnabled && !WebDriverImpl.supportsConcurrency) {
      const err = new Error(`Concurrency is not supported at the moment in ${WebDriverImpl.serviceName}. It is only supported for ChromeDriver and Selenium Server.\n`);
      err.showTrace = false;

      throw err;
    }

    return new WebDriverImpl(this.settings.webdriver);
  }
```

So it should be started in another way. The question is - How?

**Comment by mucsi96** [comment]
Can you try the same with pure Nightwatch v1. This looks like a Nightwatch issue

**Comment by ErikGrigoriev** [comment]
Ok, I'll try to check it with nightwatch.

**Comment by spnraju** [comment]
Hi @ErikGrigoriev any luck on checking with nightwatch team?

Also, I have looked at the same file in nightwatch version 1.0.11 and found that there is no implementation for Edge, IE and Opera.

This needs a fix there. 

`let browserName = this.settings.desiredCapabilities.browserName;
    let WebDriverImpl;

    switch (browserName) {
      case BrowserName.CHROME:
        WebDriverImpl = ChromeDriver;
        break;
      case BrowserName.SAFARI:
        WebDriverImpl = SafariDriver;
        break;

      case BrowserName.FIREFOX:
        WebDriverImpl = GeckoDriver;
        break;

      default:
        throw new Error(`Unsupported browser: ${browserName}. There is no available driver.`);
    }`

**Comment by mucsi96** [comment]
Any updates on this?
