### ISSUE TITLE
setup.js is not working when custom_assertions_path is introduced

### ISSUE THREAD

**Issue by ErikGrigoriev** [mucsi96/nightwatch-api#19]
Following error is coming when "custom_assertions_path" is introduced in nightwatch.conf.js:

VError: a BeforeAll hook errored, process exiting: test\support\setup.js:6: The assertion module needs to contain an .assertion() method
    at C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\cucumber\src\runtime\index.js:36:15
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
caused by: Error: The assertion module needs to contain an .assertion() method
    at AssertionLoader.validateModuleDefinition (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\assertion.js:45:13)
    at AssertionLoader.createWrapper (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\assertion.js:153:10)
    at Object.keys.forEach.namespace (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\api.js:327:14)
    at Array.forEach (<anonymous>)
    at ApiLoader.loadAssertions (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\api.js:317:47)
    at folder.forEach.item (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\api.js:309:14)
    at Array.forEach (<anonymous>)
    at ApiLoader.loadAssertions (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\api.js:308:14)
    at ApiLoader.loadCustomAssertions (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\api.js:340:12)
    at Function.init (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\api-loader\api.js:429:8)
    at NightwatchClient.loadNightwatchApis (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\index.js:359:15)
    at NightwatchClient.initialize (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\index.js:336:8)
    at Nightwatch.client (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch\lib\index.js:417:32)
    at createSession (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch-api\lib\client.js:65:35)
    at createSession (C:\dev\projects\nightwatch-api\test\nightwatch-api\examples\cucumber\node_modules\nightwatch-api\lib\index.js:40:54)
    at C:/dev/projects/nightwatch-api/test/nightwatch-api/examples/cucumber/test/support/setup.js:7:9

My setup.js:
```
import { setDefaultTimeout, AfterAll, BeforeAll } from 'cucumber';
import { createSession, closeSession } from 'nightwatch-api';

setDefaultTimeout(60000);

BeforeAll(async () => {
  await createSession('chrome');
});

AfterAll(async () => {
  await closeSession();
});
```

nightwatch.conf.js:
```
const chromedriver = require('chromedriver');
const geckodriver = require('geckodriver');

module.exports = {
    custom_assertions_path: [
        'test'
    ],
  test_settings: {
    default: {
      webdriver: {
        start_process: true,
        server_path: chromedriver.path,
        cli_args: ['--port=4444']
      },
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          args: ['headless', 'disable-gpu']
        }
      }
    },
    chrome: {
      webdriver: {
        server_path: chromedriver.path
      },
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          args: ['disable-gpu']
        }
      }
    },
    firefox: {
      webdriver: {
        server_path: geckodriver.path
      },
      desiredCapabilities: {
        browserName: 'firefox',
        marionette: true
      }
    }
  }
};
```

package.json:
```
{
  "name": "nightwatch-api-cucumber",
  "version": "1.0.0",
  "description": "Demonstration for using Nightwatch API from CucumberJS test runner",
  "main": "index.js",
  "scripts": {
    "test:setup": "babel-node test/server.js",
    "test:run": "cucumber-js --require-module babel-core/register --require test/support --require step-definitions --format node_modules/cucumber-pretty",
    "test": "start-server-and-test test:setup http-get://localhost:4444/status test:run"
  },
  "repository": "git@github.com:mucsi96/nightwatch-api.git",
  "author": "Igor Mucsicska <mucsi_96@yahoo.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "chromedriver": "^2.40.0",
    "cucumber": "^4.2.1",
    "cucumber-pretty": "^1.4.4",
    "geckodriver": "^1.12.2",
    "nightwatch": "1.0.6",
    "nightwatch-api": "latest",
    "start-server-and-test": "^1.5.0"
  }
}
```

**Comment by mucsi96** [comment]
Thanks for feedback! Can you also share the custom assertions. After that I will try to investigate the issue.

**Comment by ErikGrigoriev** [comment]
It doesn't matter. I have tested with empty .js file and even some .exe files. Still getting error. It works only if folder is empty.

**Comment by pablo-bertolami** [comment]
Hi, 
Any ideas about what cause this issue. I came across the same issue, not even using custom_assertions_path. 
But, I defined a page_objects_path.

**Comment by mucsi96** [comment]
I didn’t have time to dive into this issue. Can you help with that? An investigation and a pull request would be really welcomed 🙏

**Comment by spnraju** [comment]
Hi @ErikGrigoriev , This doesn't seem to be an issue. Would you please follow the example added as part of #102 and check if you are following the right format? Thank you!

**Comment by spnraju** [comment]
Closing this issue for now. Please feel free to let us know if you still face problem.
