### ISSUE TITLE
When assertion is failed, the script failed with exception from execa package

### ISSUE THREAD

**Issue by venba** [mucsi96/nightwatch-api#21]
I have closed the repo and installed all packages. When I ran the cucumber example, it works fine. When I change a step to make it fail , the assertion failed with exception from execa package. 

## Expected Behavior
Assertion failure message should display without npm error.

## Current Behavior
When assertion failed, I see the below error
```
> nightwatch-api-cucumber@1.0.0 test /Users/krishpra/Projects/nightwatch-api/examples/cucumber
> start-server-and-test test:setup http-get://localhost:4444/status test:run

starting server using command "npm run test:setup"
and when url "http-get://localhost:4444/status" is responding
running tests using command "test:run"

> nightwatch-api-cucumber@1.0.0 test:setup /Users/krishpra/Projects/nightwatch-api/examples/cucumber
> babel-node test/server.js


> nightwatch-api-cucumber@1.0.0 test:run /Users/krishpra/Projects/nightwatch-api/examples/cucumber
> cucumber-js --require-module babel-core/register --require test/support --require step-definitions --format node_modules/cucumber-pretty

Feature: DuckDuckGo

  Scenario: Searching DuckDuckGo
    Given I open DuckDuckGo search page
    Then the title is "DuckDuckGo — Privacy, simplified."
    And the DuckDuckGo search form exists

  Scenario: Searching DuckDuckGo again
    Given I open DuckDuckGo search page
    Then the title is "DuckDuckGo — Privacy, simplified."
    And the DuckDuckGo search form exists

Feature: Google Search

  Scenario: Searching Google
    Given I open Google`s search page
    Then the title is "Google"
    And the Google search form exists
   An error occurred while running .isVisible() command on <input[name="qm"]>: no such element: Unable to locate element: {"method":"css selector","selector":"input[name="qm"]"}
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:118:7)
✖ Testing if element <input[name="qm"]> is visible. Element could not be located. - expected "true" but got: "null"
    at World.<anonymous> (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/step-definitions/steps.js:17:23)

    ✖ failed
      Testing if element <input[name="qm"]> is visible. Element could not be located. - expected "true" but got: "null"
          at World.<anonymous> (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/step-definitions/steps.js:17:23)

  Scenario: Searching Google again
    Given I open Google`s search page
    Then the title is "Google"
    And the Google search form exists
   An error occurred while running .isVisible() command on <input[name="qm"]>: no such element: Unable to locate element: {"method":"css selector","selector":"input[name="qm"]"}
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:118:7)
✖ Testing if element <input[name="qm"]> is visible. Element could not be located. - expected "true" but got: "null"
    at World.<anonymous> (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/step-definitions/steps.js:17:23)

    ✖ failed
      Testing if element <input[name="qm"]> is visible. Element could not be located. - expected "true" but got: "null"
          at World.<anonymous> (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/step-definitions/steps.js:17:23)

Failures:

1) Scenario: Searching Google # features/google-search.feature:3
   ✔ Given I open Google`s search page # step-definitions/steps.js:4
   ✔ Then the title is "Google" # step-definitions/steps.js:12
   ✖ And the Google search form exists # step-definitions/steps.js:16
       Testing if element <input[name="qm"]> is visible. Element could not be located. - expected "true" but got: "null"
           at World.<anonymous> (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/step-definitions/steps.js:17:23)

2) Scenario: Searching Google again # features/google-search.feature:9
   ✔ Given I open Google`s search page # step-definitions/steps.js:4
   ✔ Then the title is "Google" # step-definitions/steps.js:12
   ✖ And the Google search form exists # step-definitions/steps.js:16
       Testing if element <input[name="qm"]> is visible. Element could not be located. - expected "true" but got: "null"
           at World.<anonymous> (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/step-definitions/steps.js:17:23)

4 scenarios (2 failed, 2 passed)
12 steps (2 failed, 10 passed)
0m11.871s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-api-cucumber@1.0.0 test:run: `cucumber-js --require-module babel-core/register --require test/support --require step-definitions --format node_modules/cucumber-pretty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch-api-cucumber@1.0.0 test:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krishpra/.npm/_logs/2018-09-11T20_22_21_867Z-debug.log
{ Error: Command failed: npm run test:run
    at makeError (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/Users/krishpra/Projects/nightwatch-api/examples/cucumber/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run test:run',
  timedOut: false,
  killed: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-api-cucumber@1.0.0 test: `start-server-and-test test:setup http-get://localhost:4444/status test:run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch-api-cucumber@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Steps to Reproduce (for bugs)
Change the below steps definition in cucumber example and run **npm run test** command to see the behavior.
```
Then(/^the Google search form exists$/, async () => {
  await client.assert.visible('input[name="qm"]');
});
```

**Comment by mucsi96** [comment]
You can use the `npm run` `--silent` or shorter `-s` flag to prevent showing npm ERR! output on error.
