### ISSUE TITLE
Port of webdriver should be configurable

### ISSUE THREAD

**Issue by shacall** [mucsi96/nightwatch-api#30]
## Expected Behavior
If I change the port for the webdriver in the file nightwatch.conf.js, the tests should still be executed, e.g. cli_args: ['--port=4444'] changes into cli_args: ['--port=4445']

## Current Behavior
```
The tests are not executed, but an error is delivered:
connect ECONNREFUSED 127.0.0.1:4444
   
   socket hang up
       at createHangUpError (_http_client.js:331:15)
       at Socket.socketCloseListener (_http_client.js:363:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-api-cucumber@1.0.0 e2e:setup: `babel-node test/server.js 
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nightwatch-api-cucumber@1.0.0 e2e:setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Steps to Reproduce (for bugs)
nightwatch.conf.js
```

const chromedriver = require('chromedriver');

module.exports = {
    test_settings: {
        default: {
            webdriver: {
                start_process: true,
                server_path: chromedriver.path,
                cli_args: ['--port=4445']
            },
            launch_url: 'https://www.google.at/',
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    args: ['headless', 'disable-gpu']
                }
            }
        },
        chrome: {
            webdriver: {
                server_path: chromedriver.path
            },
            launch_url: 'https://www.google.at/',
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    args: ['disable-gpu']
                }
            }
        },
        standard: {
            webdriver: {
                server_path: chromedriver.path
            },
            launch_url: 'https://derstandard.at',
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    args: ['disable-gpu']
                }
            }
        },
    }
};
```

package.json:
```
{
  "name": "nightwatch-api-cucumber",
  "version": "1.0.0",
  "description": "Demonstration for using Nightwatch API from CucumberJS test runner",
  "main": "index.js",
  "scripts": {
    "e2e:setup": "babel-node test/server.js ./test/support_files/scripts/remove-reports.js",
    "e2e:run": "E2E_ENV=$ENV cucumber-js --require-module babel-core/register --require test/support_files/setup.js --require step-definitions --format node_modules/cucumber-pretty --format json:./reports/cucumber.json $TAGS || exit 0",
    "e2e": "start-server-and-test e2e:setup http-get://localhost:4445/status e2e:run",
    "poste2e": "babel-node ./test/support_files/scripts/create-junit-report.js && node ./test/support_files/scripts/create-html-report.js"
  },
  "repository": "git@github.com:mucsi96/nightwatch-api.git",
  "author": "Igor Mucsicska <mucsi_96@yahoo.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "chromedriver": "^2.40.0",
    "cucumber": "^4.2.1",
    "cucumber-html-reporter": "^4.0.0",
    "cucumber-junit": "latest",
    "cucumber-pretty": "^1.4.4",
    "nightwatch": "^1.0.11",
    "nightwatch-api": "^0.4.0",
    "start-server-and-test": "^1.5.0"
  }
}
```
server.js
```
import { startWebDriver } from 'nightwatch-api';

startWebDriver('default').catch(err => console.log(err));

```
setup.js
```
import {setDefaultTimeout, AfterAll, After, BeforeAll, Before, Status} from 'cucumber';
import {createSession, closeSession, startWebDriver, stopWebDriver} from 'nightwatch-api';
import {client} from 'nightwatch-api';
import path from 'path';
import fs from 'fs';

setDefaultTimeout(60000);

BeforeAll(async function () {
    await createSession(process.env.E2E_ENV);
});

Before(async function () {
    await client.deleteCookies(async function (testCase) {
        console.log('\x1b[36m%s\x1b[0m', '...delete all cookies');
        await client.useCss();
    });
});

Before({tags: "@skip"}, function () {
    return 'skipped'
});

After(async function (testCase) {
    await client.deleteCookies();

    if (testCase.result.status !== Status.SKIPPED) {
        await client.execute('sessionStorage.clear()');
        await client.execute('localStorage.clear()');
    }

    if (testCase.result.status === Status.FAILED) {
        const world = this;
        const filepath = `./screenshots/${new Date().getTime()}.png`;
        await client.saveScreenshot(filepath);
        console.log(path.resolve(__dirname, '..', '..', filepath));
        world.attach(fs.readFileSync(path.resolve(__dirname, '..', '..', filepath)), 'image/png');
    }
});

AfterAll(async function () {
    await closeSession();
    await stopWebDriver();
});
```

**Comment by mucsi96** [comment]
Thanks for such detailed issue description. The issue makes sense. Any chance for a deeper investigation on this and a fix? A pull request is welcomed 😉
