### ISSUE TITLE
Getting NightwatchAssertError but the test is not reported as a failure. 

### ISSUE THREAD

**Issue by dkhabiya** [mucsi96/nightwatch-api#530]
Getting NightwatchAssertError but the test is not reported as a failure. Below is the error message we receive when the test blows up.

Version being used - 
nightwatch-api: ^2.2.1

```
[1;31m[0;31m  NightwatchAssertError: Error while running "element" command: Expected element <scenario> to be visible - element was not found - expected [0;32m"visible"[0m but got: [0;31m"not found"[0m[0m
[0;90m       at Object.element (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/commands/clearStubs.js:4:23)
at asyncGeneratorStep (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/commands/clearStubs.js:3:103)
at _next (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/commands/clearStubs.js:5:194)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)[0m[0m

```
**clearStubs** is a custom command. Below is the implementation for the same.

```
exports.command = async function (callback) {
    const baseUrl = process.env.baseUrl;
    await this.url(`${baseUrl}/stubConfiguration/update?scenario=`, callback);
    await this.expect.element('scenario').to.be.visible.before(5000);
    await this
        .getText('scenario', result => {
            console.info(`Cleaning service stub in url: ${baseUrl}/stubConfiguration/update?scenario=`);
            console.info(`Stub service using: ${result.value}`);
        });
    return this;
};
```

We also receive the below at the end of the test run

```
/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber/lib/formatter/summary_formatter.js:25
return _lodash.default.includes([_status.default.AMBIGUOUS, _status.default.FAILED], testCase.result.status);
                                                                                                                    ^
TypeError: Cannot read property 'status' of undefined
at SummaryFormatter.isTestCaseFailure (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber/lib/formatter/summary_formatter.js:25:106)
at _lodash.default.each.testCase (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber/lib/formatter/summary_formatter.js:37:16)
at /data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/lodash/lodash.js:4911:15
at baseForOwn (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/lodash/lodash.js:2996:24)
at /data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/lodash/lodash.js:4880:18
at Function.forEach (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/lodash/lodash.js:9344:14)
at SummaryFormatter.logSummary (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber/lib/formatter/summary_formatter.js:36:21)
at EventEmitter.PrettyFormatter.options.eventBroadcaster.on (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber-pretty/index.js:116:17)
at emitOne (events.js:121:20)
at EventEmitter.emit (events.js:211:7)
at Master.onSlaveClose (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber/lib/runtime/parallel/master.js:96:29)
at ChildProcess.slave.process.on (/data/jenkins/workspace/mit.nightwatch.acceptance.stubbed.bs.ipad/node_modules/cucumber/lib/runtime/parallel/master.js:83:12)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
Environment:
Node v10.15.3, MacOS 10.13.6, Chrome 74.0.3729.157

**Comment by mucsi96** [comment]
Thanks for reporting this issue. I am wondering why you need the callback in async await pattern. So my first guess is to kill it

**Comment by tosborne1215** [comment]
@mucsi96, I'm on the same project. I was wary of the async callback as well, but we see this for other verifications occasionally too. Ones that would be outside a custom command and not within a callback.

**Comment by inavac182** [comment]
Hello guys, I'm seeing a similar issue I have opened a bug in cucumber-js repo because I thought it was related to cucumber reporter https://github.com/cucumber/cucumber-js/issues/1204 but haven't got any response. Any update here about this issue?

**Comment by inavac182** [comment]
I was executing the test without parallel and was able to see this error:

```
unhandledRejection:
13:18:18    NightwatchAssertError: Error while running "waitForElementPresent" command: Timed out while waiting for element <#fsrDiv> to be present for 10000 milliseconds. - expected "found" but got: "not found"
```

and then the execution was stopped.

```
13:18:18  unhandledRejection:
13:18:18    NightwatchAssertError: Error while running "waitForElementPresent" command: Timed out while waiting for element <#fsrDiv> to be present for 10000 milliseconds. - expected "found" but got: "not found"
13:18:18        at <anonymous>
13:18:18        at process._tickCallback (internal/process/next_tick.js:188:7)
13:18:18 npm ERR! code ELIFECYCLE
13:18:18 npm ERR! errno 1
13:18:18 npm ERR! fsr-nightwatch@2.0.4 e2e-test-run: `cucumber-js `
13:18:18 npm ERR! Exit status 1
13:18:18 npm ERR! 
13:18:18 npm ERR! Failed at the fsr-nightwatch@2.0.4 e2e-test-run script.
13:18:18 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13:18:18 
13:18:18 npm ERR! A complete log of this run can be found in:
13:18:18 npm ERR!     /data/jenkins/.npm/_logs/2019-05-29T20_18_18_226Z-debug.log
13:18:18 
13:18:18 > node create-html-report.js
13:18:18 
13:18:18 module.js:674
13:18:18     throw err;
13:18:18     ^
13:18:18 
13:18:18 SyntaxError: /reports/cucumber.json: Unexpected end of JSON input
13:18:18     at JSON.parse (<anonymous>)
```

So, probably the issue I'm facing is the same than the one in this thread.

**Comment by inavac182** [comment]
More info for previous comment, the line that is throwing the `unhandledRejection: NightwatchAssertError ` is:

```
await browser.waitForElementPresent('@ fsrDiv', 10000);
```
I tried using the expect, but got the same result
```
await browser.expect.element('@ fsrDiv').to.be.present.before(10000);
```

**Comment by inavac182** [comment]
FYI guys, after a lot of investigation we found that our issue was caused because one of the steps previous to this one that failed has an async/await statement in the callback. So, we modify it and then this step was able to fail but not break the execution and that way we were able to get the report.

**Comment by dkhabiya** [comment]
After making the suggested changes we were able to solve this issue. Closing this one. Thank you!
