### ISSUE TITLE
Error Screenshot Name Too Long

### ISSUE THREAD

**Issue by tosborne1215** [mucsi96/nightwatch-api#554]
## Expected Behavior

A verification is failing that is verifying the text of a paragraph and the screenshot name appears to contain the text of the paragraph which is too long to be a file name. Maybe hashing this value would be a better approach?

## Steps to Reproduce (for bugs)

```
const msg = 'A verification is failing that is verifying the text of a paragraph and the screenshot name appears to contain the text of the paragraph which is too long to be a file name. Maybe hashing this value would be a better approach?';

// .paragraph does not exist on the page
await browser.expect.element('.paragraph').text.to.contain(msg);
```

Which results in an error like when it retrieves the screenshots.

```
01:47:14 Error: ENAMETOOLONG: name too long, open 'reports/screenshots/A_verification_is_failing_that_is_verifying_the_text_of_a_paragraph_and_the_screenshot_name_appears_to_contain_the_text_of_the_paragraph_which_is_too_long_to_be_a_file_name_Maybe_hashing_this_value_would_be_a_better_approach.png'
01:47:14     at Object.fs.openSync (fs.js:646:18)
01:47:14     at Object.fs.writeFileSync (fs.js:1299:33)
01:47:14     at /node_modules/cucumber-html-reporter/lib/reporter.js:278:40
01:47:14     at Array.forEach (<anonymous>)
01:47:14     at /node_modules/cucumber-html-reporter/lib/reporter.js:233:41
01:47:14     at Array.forEach (<anonymous>)
01:47:14     at /node_modules/cucumber-html-reporter/lib/reporter.js:231:31
01:47:14     at Array.forEach (<anonymous>)
01:47:14     at /node_modules/cucumber-html-reporter/lib/reporter.js:218:30
01:47:14     at Array.forEach (<anonymous>)
```

## Your Environment

We recently updated to consume the `getNewScreenshots()` function. It is unclear if this bug reproduces in earlier versions.

```
    "browsermob-proxy-api": "^0.4.0",
    "browserstack-local": "^1.3.7",
    "chai": "^4.2.0",
    "chromedriver": "^74.0.0",
    "cucumber": "^5.1.0",
    "cucumber-analysis": "^1.0.6",
    "cucumber-html-reporter": "^4.0.2",
    "cucumber-pretty": "^1.5.0",
    "dotenv-safe": "^6.1.0",
    "geckodriver": "^1.16.2",
    "iedriver": "^3.14.1",
    "moment": "^2.24.0",
    "nightwatch": "^1.1.11",
    "nightwatch-accessibility": "^1.8.0",
    "nightwatch-api": "^2.3.0",
    "selenium-server-standalone-jar": "^3.141.5",
    "selenium-webdriver": "^3.6.0"
```
- Browser Name and version: All
- Operating System and version (desktop or mobile): MacOS/Linux Desktop

**Comment by spnraju** [comment]
Hello @tosborne1215, do you still see this issue with the latest Nightwatch version?
