### ISSUE TITLE
Error: Cannot find module 'nightwatch/lib/api/protocol'

### ISSUE THREAD

**Issue by DustinOgan** [mucsi96/nightwatch-api#819]
upgrading to try 1.3.0 this morning, this error is being returned:
Error: Cannot find module 'nightwatch/lib/api/protocol'

Returning to my previous used version @1.2.1 of nightwatch returns the tests to a working state.  This is more of a heads up currently than a bug report. As it appears to be a breaking change on the part of nightwatch removing or moving a dependency 

> mkdirp report && cucumber-js --require cucumber.conf-openingQA.js --require open-proc-step-defs/ --format node_modules/cucumber-pretty --format json:report/openprocqa_report.json "--tags" "@discovery"'

Error: Cannot find module 'nightwatch/lib/api/protocol'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\MyUser\Documents\gherkin-demo\node_modules\nightwatch-api\lib\client.js:16:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\MyUser\Documents\gherkin-demo\node_modules\nightwatch-api\lib\index.js:13:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

**Comment by mucsi96** [comment]
Thanks for reporting this! Appreciate that. Will take a look asap. Will let you know if it's resolved

**Comment by tosborne1215** [comment]
@mucsi96 my team was looking at this issue. That 'module' in nightwatchjs is no longer a module. Instead it is a folder broken out into multiple files. It might just start working if nightwatchjs added an index.js to the folder `nightwatch/lib/api/protocol`

@DustinOgan To resolve this we downgraded from nightwatch 1.3.0 to 1.2.4

**Comment by mucsi96** [comment]
Should be fixed now. Try to update `nightwatch-api` to latest version `3.0.1`

**Comment by mucsi96** [comment]
To prevent such issues in future please consider voting for this https://github.com/nightwatchjs/nightwatch/issues/2254#issuecomment-557712943
